/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_accept[250] =
    {   0,
        0,    0,   96,   95,    1,   89,   76,   88,   78,   71,
       95,   38,   39,   72,   73,   87,   74,   70,   77,   91,
       91,   84,   85,   79,   86,   80,   83,   90,   90,   36,
       37,   81,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   40,   82,   41,
       75,   53,   64,   69,   58,   68,   54,   61,    0,    0,
       56,   46,   59,   47,   60,    0,   57,    0,   91,    0,
       91,   91,   66,   67,   65,   48,   50,   52,   51,   49,
       90,    0,    0,    0,   62,   90,   90,   90,   90,   90,
       90,    9,   90,   90,   90,   90,   90,   90,   17,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   63,   55,    0,   93,   43,   92,   91,   91,   91,
       91,   44,   45,    0,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   15,   90,   90,   19,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   42,    0,   92,   91,   91,
       91,   91,    0,    2,   90,    4,    5,   90,   90,   90,
       90,   11,   12,   90,   90,   16,   90,   20,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       33,   90,   90,    0,   92,   91,    0,    3,    6,   90,

       90,   90,   90,   14,   90,   90,   90,   90,   24,   90,
       90,   90,   90,   90,   90,   31,   90,   90,   35,   94,
       90,   90,   10,   13,   18,   90,   90,   23,   25,   26,
       27,   28,   29,   90,   90,   90,   90,    8,   90,   90,
       30,   90,   90,    7,   21,   22,   32,   34,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    4,    5,
        6,    7,    8,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   10,   11,   12,    1,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       25,   25,   25,   25,   25,   26,   27,   28,   29,   30,
       31,   32,   33,    1,   34,   34,   34,   34,   35,   36,
       37,   37,   37,   37,   37,   38,   37,   37,   37,   37,
       37,   37,   37,   37,   39,   37,   37,   40,   37,   37,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   37,   55,   56,   57,   58,
       59,   60,   37,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[74] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    3,    2,    2,    3,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    2,    3,    3,    3,    3,
        3,    3,    3,    2,    3,    3,    3,    3,    3,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[253] =
    {   0,
        0,    0,  357,  358,  358,  358,  325,  343,   46,   61,
       78,  358,  358,  323,   57,  358,   58,  331,  321,   72,
       78,  319,  358,   78,  319,   82,  358,    0,   75,  305,
      358,  317,  283,  285,   64,   65,   62,   63,  286,   70,
      285,  293,   72,  274,  115,  282,  287,  358,   56,  358,
      358,  358,  358,  326,  358,  358,  358,  358,  323,  322,
      358,  358,  358,  358,  358,  314,  358,  107,  118,  124,
       98,  133,  358,  358,  358,  304,  358,  358,  358,  303,
        0,  161,  289,  321,  358,  268,  280,  267,  282,  269,
      275,  261,  262,  259,  259,  262,  259,  256,    0,  114,

      260,  109,  258,  122,  129,  262,  255,  273,  124,  125,
      259,  358,  358,  284,  358,  358,  171,  144,  146,  149,
      160,  358,  358,  269,  251,  263,  258,  246,   90,  260,
      258,  254,  246,  252,  255,    0,  241,  245,    0,  246,
      243,  233,  231,  233,  235,  242,  228,  226,  226,  238,
      228,  232,  236,  238,  227,  358,  193,  358,  149,  358,
      244,  225,  237,    0,  224,    0,    0,  215,  223,  212,
      219,    0,    0,  213,  210,    0,  214,    0,  209,  209,
      208,  205,  217,  207,  205,  210,  209,  207,  196,  201,
        0,  189,  201,  177,  204,  358,  231,    0,    0,  191,

      192,  197,  188,    0,  195,  181,  189,  183,    0,  190,
      187,  189,  173,  182,  184,    0,  175,  178,    0,  358,
      162,  162,    0,    0,    0,  173,  167,    0,    0,    0,
        0,    0,    0,  160,  143,  136,  139,    0,  119,   84,
        0,   58,   51,    0,    0,    0,    0,    0,  358,  260,
      262,   93
    } ;

static yyconst short int yy_def[253] =
    {   0,
      249,    1,  249,  249,  249,  249,  249,  249,  249,  249,
      250,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  251,  251,  249,
      249,  249,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      252,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      251,  250,  249,  249,  249,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  249,  249,  249,  249,  249,  249,  252,  249,  249,
      249,  249,  249,  249,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  249,  249,  249,  249,  249,
      249,  249,  249,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  249,  249,  249,  249,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  249,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,    0,  249,
      249,  249
    } ;

static yyconst short int yy_nxt[432] =
    {   0,
        4,    4,    4,    4,    5,    4,    4,    4,    6,    7,
        4,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   28,   28,   29,   29,   28,
       30,    4,   31,   32,   28,   33,   34,   35,   36,   37,
       38,   39,   28,   40,   28,   41,   28,   28,   28,   28,
       42,   43,   44,   45,   46,   47,   28,   28,   28,   48,
       49,   50,   51,   54,   57,   62,   55,   56,   64,   60,
       60,   60,   60,   60,   60,   60,  112,   63,   65,   82,
       74,   58,   60,   68,  118,   69,   69,   70,   70,   68,

      248,   72,   72,   72,   72,   75,  247,   76,   77,   88,
       60,   71,   79,   80,   91,   83,   89,   93,   96,   94,
       99,   97,   90,   92,  103,  104,  113,  100,   95,   82,
      117,  117,  117,  117,  105,  119,  120,  106,   71,   68,
      108,   69,   69,   70,   70,   68,  246,   70,   70,   70,
       70,  168,  169,  121,   68,   83,   72,   72,   72,   72,
      141,  120,   60,   60,   60,   60,   60,   60,   60,  138,
      142,  143,  109,  145,  147,   60,  139,  151,  153,  245,
      154,  119,  120,  159,  160,  152,  161,  160,  244,  148,
      146,  243,  242,   60,  117,  117,  117,  117,  160,  121,

      195,  195,  195,  195,  162,  157,  158,  120,  158,  160,
      241,  194,  160,  194,  240,  159,  195,  195,  195,  195,
      157,  158,  239,  160,  238,  237,  158,  195,  195,  195,
      195,  236,  235,  234,  233,  232,  231,  230,  229,  158,
      228,  158,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  158,  215,  214,  213,  212,  158,
       59,   59,   59,   81,   81,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  196,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,

      175,  174,  173,  172,  171,  170,  167,  166,  165,  164,
      163,  156,  155,   83,  150,  149,  144,  140,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  127,  126,
      125,  124,   84,  123,  122,  116,  115,  115,  114,  111,
      110,  107,  102,  101,   98,   87,   86,   85,   84,   78,
       73,   67,   66,   61,   53,   52,  249,    3,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249
    } ;

static yyconst short int yy_chk[432] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,   10,   15,    9,    9,   17,   11,
       11,   11,   11,   11,   11,   11,   49,   15,   17,   29,
       24,   10,   11,   20,  252,   20,   20,   20,   20,   21,

      243,   21,   21,   21,   21,   24,  242,   24,   24,   35,
       11,   20,   26,   26,   36,   29,   35,   37,   38,   37,
       40,   38,   35,   36,   43,   43,   49,   40,   37,   45,
       68,   68,   68,   68,   43,   71,   71,   43,   20,   69,
       45,   69,   69,   69,   69,   70,  240,   70,   70,   70,
       70,  129,  129,   71,   72,   45,   72,   72,   72,   72,
      102,   71,   82,   82,   82,   82,   82,   82,   82,  100,
      102,  102,   45,  104,  105,   82,  100,  109,  110,  239,
      110,  118,  118,  119,  119,  109,  120,  159,  237,  105,
      104,  236,  235,   82,  117,  117,  117,  117,  121,  118,

      194,  194,  194,  194,  120,  117,  117,  118,  117,  119,
      234,  157,  159,  157,  227,  121,  157,  157,  157,  157,
      117,  117,  226,  121,  222,  221,  117,  195,  195,  195,
      195,  218,  217,  215,  214,  213,  212,  211,  210,  195,
      208,  195,  207,  206,  205,  203,  202,  201,  200,  197,
      193,  192,  190,  189,  195,  188,  187,  186,  185,  195,
      250,  250,  250,  251,  251,  184,  183,  182,  181,  180,
      179,  177,  175,  174,  171,  170,  169,  168,  165,  163,
      162,  161,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  138,  137,

      135,  134,  133,  132,  131,  130,  128,  127,  126,  125,
      124,  114,  111,  108,  107,  106,  103,  101,   98,   97,
       96,   95,   94,   93,   92,   91,   90,   89,   88,   87,
       86,   84,   83,   80,   76,   66,   60,   59,   54,   47,
       46,   44,   42,   41,   39,   34,   33,   32,   30,   25,
       22,   19,   18,   14,    8,    7,    3,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\main.l"
#define INITIAL 0
#line 2 ".\\main.l"
    #include<stdio.h>
    #include<stdlib.h>
    #include<string.h>
    FILE* fp;
    int row=1,col=0,cnt=0;
    void printToken(char*,char*);
#line 551 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 ".\\main.l"

#line 704 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 250 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 358 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 ".\\main.l"
{++row; col=0;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 ".\\main.l"
{printToken(yytext,"'auto'");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 ".\\main.l"
{printToken(yytext,"'break'");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 ".\\main.l"
{printToken(yytext,"'case'");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 ".\\main.l"
{printToken(yytext,"'char'");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 ".\\main.l"
{printToken(yytext,"'const'");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 31 ".\\main.l"
{printToken(yytext,"'continue'");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 ".\\main.l"
{printToken(yytext,"'default'");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 ".\\main.l"
{printToken(yytext,"'do'");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 ".\\main.l"
{printToken(yytext,"'double'");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 ".\\main.l"
{printToken(yytext,"'else'");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 ".\\main.l"
{printToken(yytext,"'enum'");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 ".\\main.l"
{printToken(yytext,"'extern'");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 ".\\main.l"
{printToken(yytext,"'float'");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 ".\\main.l"
{printToken(yytext,"'for'");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 ".\\main.l"
{printToken(yytext,"'goto'");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 ".\\main.l"
{printToken(yytext,"'if'");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 ".\\main.l"
{printToken(yytext,"'inline'");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 ".\\main.l"
{printToken(yytext,"'int'");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 ".\\main.l"
{printToken(yytext,"'long'");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 ".\\main.l"
{printToken(yytext,"'register'");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 ".\\main.l"
{printToken(yytext,"'restrict'");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 47 ".\\main.l"
{printToken(yytext,"'return'");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 48 ".\\main.l"
{printToken(yytext,"'short'");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 49 ".\\main.l"
{printToken(yytext,"'signed'");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 50 ".\\main.l"
{printToken(yytext,"'sizeof'");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 51 ".\\main.l"
{printToken(yytext,"'static'");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 52 ".\\main.l"
{printToken(yytext,"'struct'");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 53 ".\\main.l"
{printToken(yytext,"'switch'");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 54 ".\\main.l"
{printToken(yytext,"'typedef'");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 55 ".\\main.l"
{printToken(yytext,"'union'");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 56 ".\\main.l"
{printToken(yytext,"'unsigned'");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 57 ".\\main.l"
{printToken(yytext,"'void'");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 58 ".\\main.l"
{printToken(yytext,"'volatile'");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 59 ".\\main.l"
{printToken(yytext,"'while'");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 60 ".\\main.l"
{printToken(yytext,"'['");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 61 ".\\main.l"
{printToken(yytext,"']'");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 62 ".\\main.l"
{printToken(yytext,"'('");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 63 ".\\main.l"
{printToken(yytext,"')'");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 64 ".\\main.l"
{printToken(yytext,"'{'");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 65 ".\\main.l"
{printToken(yytext,"'}'");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 66 ".\\main.l"
{printToken(yytext,"'%:%:'");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 67 ".\\main.l"
{printToken(yytext,"'...'");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 68 ".\\main.l"
{printToken(yytext,"'<<='");}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 69 ".\\main.l"
{printToken(yytext,"'>>='");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 70 ".\\main.l"
{printToken(yytext,"'++'");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 71 ".\\main.l"
{printToken(yytext,"'--'");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 72 ".\\main.l"
{printToken(yytext,"'<<'");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 73 ".\\main.l"
{printToken(yytext,"'>>'");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 74 ".\\main.l"
{printToken(yytext,"'<='");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 75 ".\\main.l"
{printToken(yytext,"'>='");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 76 ".\\main.l"
{printToken(yytext,"'=='");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 77 ".\\main.l"
{printToken(yytext,"'!='");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 78 ".\\main.l"
{printToken(yytext,"'&&'");}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 79 ".\\main.l"
{printToken(yytext,"'||'");}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 80 ".\\main.l"
{printToken(yytext,"'*='");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 ".\\main.l"
{printToken(yytext,"'/='");}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 ".\\main.l"
{printToken(yytext,"'%='");}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 ".\\main.l"
{printToken(yytext,"'+='");}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 84 ".\\main.l"
{printToken(yytext,"'-='");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 85 ".\\main.l"
{printToken(yytext,"'&='");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 86 ".\\main.l"
{printToken(yytext,"'^='");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 87 ".\\main.l"
{printToken(yytext,"'|='");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 88 ".\\main.l"
{printToken(yytext,"'##'");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 89 ".\\main.l"
{printToken(yytext,"'<:'");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 90 ".\\main.l"
{printToken(yytext,"':>'");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 91 ".\\main.l"
{printToken(yytext,"'<%'");}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 92 ".\\main.l"
{printToken(yytext,"'%>'");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 93 ".\\main.l"
{printToken(yytext,"'%:'");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 94 ".\\main.l"
{printToken(yytext,"'.'");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 95 ".\\main.l"
{printToken(yytext,"'&'");}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 96 ".\\main.l"
{printToken(yytext,"'*'");}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 97 ".\\main.l"
{printToken(yytext,"'+'");}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 98 ".\\main.l"
{printToken(yytext,"'-'");}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 99 ".\\main.l"
{printToken(yytext,"'~'");}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 100 ".\\main.l"
{printToken(yytext,"'!'");}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 101 ".\\main.l"
{printToken(yytext,"'/'");}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 102 ".\\main.l"
{printToken(yytext,"'%'");}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 103 ".\\main.l"
{printToken(yytext,"'<'");}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 104 ".\\main.l"
{printToken(yytext,"'>'");}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 105 ".\\main.l"
{printToken(yytext,"'^'");}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 106 ".\\main.l"
{printToken(yytext,"'|'");}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 107 ".\\main.l"
{printToken(yytext,"'?'");}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 108 ".\\main.l"
{printToken(yytext,"':'");}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 109 ".\\main.l"
{printToken(yytext,"';'");}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 110 ".\\main.l"
{printToken(yytext,"'='");}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 111 ".\\main.l"
{printToken(yytext,"','");}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 112 ".\\main.l"
{printToken(yytext,"'#'");}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 113 ".\\main.l"
{++col;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 114 ".\\main.l"
{printToken(yytext,"IDENTIFIER");}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 115 ".\\main.l"
{printToken(yytext,"INTEGER_CONSTANT");}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 116 ".\\main.l"
{printToken(yytext,"FLOATING_CONSTANT");}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 117 ".\\main.l"
{printToken(yytext,"CHARACTER_CONSTANT");}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 118 ".\\main.l"
{printToken(yytext,"STRING_LITERAL");}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 119 ".\\main.l"
ECHO;
	YY_BREAK
#line 1262 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 250 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 250 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 249);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 119 ".\\main.l"


int main() {
    yyin=fopen("./test.c","r");
    fp=fopen("./test.tokens","w");
    yylex();
    return 0;
}

void printToken(char* cont, char* type) {
    int end_col=col+strlen(cont);
    fprintf(fp,"[@%d,%d:%d='%s',<%s>,%d:%d]\n", cnt, col, end_col, cont, type, row, col);
    ++cnt;
    col+=strlen(cont);
}

int yywrap(){
    printToken("<EOF>","EOF");
	return 1;
}